# Generated by Django 2.1.5 on 2019-02-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blip_core', '0004_eventattendees_attended_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not prefer to say')], default='N', max_length=1),
        ),
    ]
