# Generated by Django 2.1.5 on 2019-02-06 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippet',
            name='session',
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='extension',
            field=models.CharField(default='py', max_length=5),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='language',
            field=models.CharField(max_length=10),
        ),
    ]
