# Generated by Django 2.1.5 on 2019-02-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blip_core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('snippet', models.TextField()),
                ('language', models.CharField(choices=[('js', 'JavaScript '), ('php', 'PHP'), ('xml', 'XML'), ('py', 'Python')], max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blip_core.Event')),
            ],
        ),
        migrations.CreateModel(
            name='SeminarSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('participant_count', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blip_core.Event')),
            ],
        ),
    ]
